= Installing AsciiDoc 

When we talk about installing AsciiDoc, we refer to the AsciiDoc interpreter that understands the source files written in AsciiDoc and can convert them into a format more suitable for publishing, such as `html`, `epub`, or `pdf`. 

For our purposes, we will use the AsciiDoctor interpreter.

== Installing AsciiDoctor on Linux.

Various Linux distribution use various package managers to install new packages and programs. Although AsciiDoctor can be installed using the Ruby installation procedure with `gem`, try to use your system's package manager first. This way, you will always automatically install all needed dependencies and you will receive update automatically, if you update your system.

=== Before you start

. Your user account must be allowed to run the `sudo` command. If you are not sure, please ask your computer administrator.
. Open a terminal window. If you do not know what a terminal window is:
.. Press *Alt-F2* to open a program launcher. 
.. Type `gnome-terminal` in the program launcher and hit *Enter*.
.. The terminal window opens and you are ready to go.

=== Installation

You can install the `asciidoctor` package using your Linux distribution package manager. 

. In Fedora Linux use:
+
----
$ sudo dnf install asciidoctor
----

. In Debian or Ubuntu Linux use:  
+
----
$ sudo apt-get install asciidoctor
----

. In ArchLinux, make sure that you have enabled the `community` repository and use. 
+
----
$ sudo pacman -S asciidoctor
----


Your AsciiDoctor interpreter is now installed.

=== Installing AsciiDoctor using the Ruby installer `gem`.

Some systems do not use their package managers, or AsciiDoctor is not part of their repositories, in that case, you will have to use the Ruby `gem` installator.

. In Red Hat Enterprise Linux:
.. Install *Ruby* first:
+
----
$ sudo yum install ruby
----
.. Install *AsciiDoctor* using the Ruby installator, `gem`:
+
----
$ gem asciidoctor
----
.. If there is a new version of AsciiDoctor, you will have to manually update by using:
+
----
$ gem update asciidoctor
----

. In Windows, use the https://rubyinstaller.org/[Ruby Installer] to install *Ruby* on your system. Then follow the above instructions.

. In MacOS, use the http://rvm.io/[Ruby Version Manager] to install *Ruby* and follow the above instructions. 
