== Installing AsciiDoc 

When we talk about installing AsciiDoc, we refer to the AsciiDoc interpreter that understands the source files written in AsciiDoc and can convert them into a format more suitable for publishing, such as `html`, `epub`, or `pdf`. 

For our purposes, we will use the AsciiDoctor interpreter.

=== Installing AsciiDoctor on Linux.

Various Linux distribution use various package managers to install new packages and programs. Although AsciiDoctor can be installed using the Ruby installation procedure with `gem`, try to use your system's package manager first. This way, you will always automatically install all needed dependencies and you will receive update automatically, if you update your system.

==== Installing AsciiDoctor on Fedora Linux

.Before you start

. Your user account must be allowed to run the `sudo` command. If you are not sure, please ask your computer administrator.
. Open a terminal window. If you do not know what a terminal window is:
.. Press *Alt-F2* to open a program launcher. 
.. Type `gnome-terminal` in the program launcher and hit *Enter*.
.. The terminal window opens and you are ready to go.

To install AsciiDoctor on your Fedora using the *dnf* package manager:

. Install the `asciidoctor` package. You do it by entering the following command in the terminal window. 
+
----
$ sudo dnf install asciidoctor
----


. 
. Call the `gnome-terminal` termi

 



