= Using AsciiDoc and AsciiDoctor to create documents.

Unlike working with word processors, that instantly show you the output of the edited document (the WYSIWYG method), using AsciiDoc is different. The typical working process consists of two main parts.

== Writing AsciiDoc source files

The content of your document consists of one or more files in plain text, to which you add some special characters. These are needed to define the structure of the document and how particular text elements will be rendered in the file document, for example *bold*, _italic_, or `typewritten` text. It is usual to save such a source file with the `adoc` suffix. 

Even if you do not add any special characters to mark individual elements, text only can be rendered by AsciiDoctor into the final output, be it a *pdf*, *docbook*, or *html*.

A comprehensive overview of the AsciiDoc markup is beyond this document. Please, read the basic rules in the link:http://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc Writers' Guide]. 

== Rendering the output

Once you have some source files ready, you can process the with *AsciiDoctor* and get the final output. Basically, you can choose between several target formats. Converting the source files into the target format is very easy. You only have to run *AsciiDoctor* and point it to the file, that you want to have rendered.

----
$ asciidoctor my_file.adoc
----

By default, *AsciiDoctor* will convert the document into HTML5. You can change this behaviour by telling *AsciiDoctor* which output you want to get by adding the `-b` option and the target format to the original command.

----
$ asciidoctor -b <target_format> my_file.adoc
----

This table shows possible target formats and their command-line aliases.

|===
| Format | CLI alias
| HTML (version 5) a| `html` or `html5`
| DocBook (version 4.5) a| `docbook45`
| DocBook (version 5) a| `docbook` or `docbook5`
| Manual Pages a| `manpage` 
|===

Normally, *AsciiDoctor* will take the source file and create the output file in the same location and under the same name with a different extension. For example, the `my_file.adoc` file that should be rendered into a *html* output becomes the `my_file.html` file in the same directory. To override this behaviour, you can add the `-o` option and specify a different name and location of the output file.

----
$ asciidoctor -o /home/user/html/my_html_file.html my_file.adoc
---- 

=== Rendering the PDF output

If you need to create a *pdf* file, you do it the same way, but you have to use a special *AsciiDoctor* command to create the desired output. 

----
$ asciidoctor-pdf my_file.adoc
---- 

This will create a *pdf* file next to the source file.
