== Using AsciiDoc and Asciidoctor to create documents.

Unlike working with word processors, that instantly show you the output of the edited document (the WYSIWYG method), using AsciiDoc is different. The typical working process consists of two main parts.

=== Writing AsciiDoc source files

The content of your document consists of one or more files in plain text, to which you add some special characters. These are needed to define the structure of the document and how particular text elements will be rendered in the file document, for example *bold*, _italic_, or `typewritten` text. It is usual to save such a source file with the `adoc` suffix. 

Even if you do not add any special characters to mark individual elements, text only can be rendered by AsciiDoctor into the final output, be it a *pdf*, *docbook*, or *html*.

A comprehensive overview of the AsciiDoc markup is beyond this document. Please, read the basic rules in the link:http://asciidoctor.org/docs/asciidoc-writers-guide/[AsciiDoc Writers' Guide]. 

=== Rendering the output

Once you have some source files ready, you can process the with *AsciiDoctor* and get the final output. Basically, you can choose between several target formats. Converting the source files into the target format is very easy. You only have to run *AsciiDoctor* and point it to the file, that you want to have rendered.

----
$ asciidoctor my_file.adoc
----

By default, *AsciiDoctor* will convert the document into HTML5. You can change this behaviour by telling *AsciiDoctor* which output you want to get by adding the `-b` option and the target format to the original command.

----
$ asciidoctor -b _<target_format>_ my_file.adoc
----



. HTML version 5 (by default)
. DocBook version 4.5
. DocBook version 5
. Manual Pages
. Portable Document Format (pdf)

The 

